// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<Uint8List> readImage(String path) =>
    RustLib.instance.api.crateApiCoreReadImage(path: path);

Future<(String, double)> getImageNameAndSize(String path) =>
    RustLib.instance.api.crateApiCoreGetImageNameAndSize(path: path);

Future<String> changeFilenameExtension(String filename, String extension_) =>
    RustLib.instance.api.crateApiCoreChangeFilenameExtension(
      filename: filename,
      extension_: extension_,
    );
