// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Callbacks`, `WebSocketHandler`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `drop`, `fmt`, `fmt`, `from`, `from`, `on_binary`, `on_call`, `on_close`, `on_connect_fail`, `on_connect`, `on_text`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<WebSocketClient>>
abstract class WebSocketClient implements RustOpaqueInterface {
  /// Quick connect method - creates and connects in one step
  static Future<WebSocketClient> connect(String url) =>
      RustLib.instance.api.crateApiWebsocketWebSocketClientConnect(url: url);

  /// Connect to the WebSocket server with the pre-configured callbacks
  Future<void> connectTo(String url);

  /// Debug method to check which callbacks are registered
  String getListenersStatus();

  /// Create a new WebSocketClient without connecting yet.
  /// Set up all event listeners, then call connect_to().
  factory WebSocketClient() =>
      RustLib.instance.api.crateApiWebsocketWebSocketClientNew();

  void onBinary(FutureOr<void> Function(Uint8List) func);

  void onClose(FutureOr<void> Function(CloseFrame?) func);

  void onConnect(FutureOr<void> Function() func);

  void onConnectionFailed(FutureOr<void> Function(WSError) func);

  void onDisconnect(FutureOr<void> Function() func);

  void onText(FutureOr<void> Function(String) func);

  Future<void> sendText(String text);
}

class CloseFrame {
  final int code;
  final String reason;

  const CloseFrame({required this.code, required this.reason});

  @override
  int get hashCode => code.hashCode ^ reason.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CloseFrame &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          reason == other.reason;
}

class WSError {
  final String message;

  const WSError({required this.message});

  @override
  int get hashCode => message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WSError &&
          runtimeType == other.runtimeType &&
          message == other.message;
}
