name: "Build & Release"

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'

permissions:
  contents: write
  
jobs:  
  build:      
    name: Build & Release  
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set Up Java
        uses: actions/setup-java@v3.12.0
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: aarch64-linux-android,armv7-linux-androideabi,x86_64-linux-android,i686-linux-android

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          version: latest
      
      - name: Install Dependencies
        run: flutter pub get

      - name: Accept Android Licenses
        run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/keystore.jks
      
      - name: Create key.properties
        run: |
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=keystore.jks" >> android/key.properties

      - name: Decode Firebase Configuration Files
        run: |
          echo "Decoding google-services.json..."
          echo -n "${{ secrets.GOOGLE_SERVICE_JSON }}" | base64 --decode > android/app/google-services.json
          echo "Decoding firebase_options.dart..."
          echo -n "${{ secrets.FIREBASE_OPTIONS }}" | base64 --decode > lib/firebase_options.dart
          echo "Decoding GoogleService-Info.plist..."
          echo -n "${{ secrets.GOOGLE_SERVICE_PLIST }}" | base64 --decode > ios/Runner/GoogleService-Info.plist
          echo "Verifying decoded files..."
          ls -lh android/app/google-services.json
          ls -lh lib/firebase_options.dart
          ls -lh ios/Runner/GoogleService-Info.plist
          echo "Checking firebase_options.dart content (first 5 lines):"
          head -n 5 lib/firebase_options.dart || echo "File is empty or unreadable"

      - name: Build APK
        run: flutter build apk --release --build-name="${{ github.event.inputs.version || github.ref_name }}" --build-number="${{ github.run_number }}"

      - name: Build App Bundle
        run: flutter build appbundle --release --build-name="${{ github.event.inputs.version || github.ref_name }}" --build-number="${{ github.run_number }}"

      - name: Build iOS IPA (No Code Sign)
        run: flutter build ipa --release --no-codesign --build-name="${{ github.event.inputs.version || github.ref_name }}" --build-number="${{ github.run_number }}"

      - name: Package IPA from Archive
        run: |
          cd build/ios/archive
          ARCHIVE_NAME=$(ls -t | grep ".xcarchive" | head -n 1)
          echo "Found archive: $ARCHIVE_NAME"
          mkdir -p Payload
          cp -r "$ARCHIVE_NAME/Products/Applications/Runner.app" Payload/
          zip -r Runner.ipa Payload
          mv Runner.ipa ../../../
          cd ../../..
          echo "IPA created at: $(pwd)/Runner.ipa"
          ls -lh Runner.ipa

      - name: Get Release Version
        id: version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          else
            echo "version=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          fi

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: Release ${{ steps.version.outputs.version }}
          draft: false
          prerelease: false
          files: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/bundle/release/app-release.aab
            Runner.ipa
          token: ${{ secrets.GITHUB_TOKEN }}